title: LogNow!
description: Documentación técnica de la App de seguimiento de videojuegos.
plugins:
  - jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs

search:
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
head_scripts:
  - "/assets/css/custom.css"